name: Ping Command
on:
  repository_dispatch:
    types: [ping-local-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body-includes: This comment was written by a bot!

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          This comment was written by a bot!
        reactions: rocket

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          This comment has been updated!
          Note: This comment was written by a bot!
        reactions: hooray
